CREATE TABLE VOTING_CARD_STATE
(
    ELECTION_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ID         VARCHAR2(255 CHAR) NOT NULL,
    VOTING_CARD_ID    VARCHAR2(255 CHAR) NOT NULL,
    ATTEMPTS          NUMBER(19,0),
    STATE             VARCHAR2(255 CHAR),
    PRIMARY KEY (ELECTION_EVENT_ID, TENANT_ID, VOTING_CARD_ID)
);

CREATE TABLE PLATFORM_CERTIFICATE
(
    ID                  NUMBER(19,0) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLATFORM_CERTIFICATE_UK1 UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);

CREATE SEQUENCE PLATFORM_CERTIFICATE_SEQ;
