CREATE TABLE EXTENDED_AUTHENTICATION
(
    EXTRA_PARAM    VARCHAR2(200 BYTE),
    ATTEMPTS       INTEGER NOT NULL,
    TENANT_ID      VARCHAR2(100 BYTE) NOT NULL,
    ELECTION_EVENT VARCHAR2(100 BYTE) NOT NULL,
    SALT           VARCHAR2(200 BYTE),
    ENCRYPTED_SVK  VARCHAR2(150 BYTE) NOT NULL,
    AUTH_ID        VARCHAR2(100 BYTE) NOT NULL,
    CREDENTIAL_ID  VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT EXTENDED_AUTHENTICATION_PK PRIMARY KEY (ELECTION_EVENT, TENANT_ID, AUTH_ID)
);

CREATE SEQUENCE EA_PLATFORM_CERTIFICATES_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE;

CREATE TABLE EA_PLATFORM_CA_CERTIFICATES
(
    ID                  NUMBER(11,0) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100) NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT EA_PLATFORMCA_CERTIFICATES_UK UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);