CREATE TABLE AUTHENTICATION_CERTS
(
    ID                NUMBER(10,0) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    SIGNATURE         CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT AUTHENTICATION_CERTS_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID)
);

CREATE TABLE AUTHENTICATION_CONTENT
(
    ID                NUMBER(10,0) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT AUTHENTICATION_CONTENT_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID)
);

CREATE TABLE PLATFORM_CERTIFICATE
(
    ID                  NUMBER(19,0) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLATFORM_CERTIFICATE_UK1 UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);

CREATE TABLE TENANT_KEYSTORE
(
    ID               NUMBER(19,0) NOT NULL,
    KEY_TYPE         VARCHAR2(100 CHAR) NOT NULL,
    KEYSTORE_CONTENT CLOB NOT NULL,
    PLATFORM_NAME    VARCHAR2(100 CHAR),
    TENANT_ID        VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT TENANT_KEYSTORE_UK1 UNIQUE (PLATFORM_NAME, KEY_TYPE, TENANT_ID)
);

CREATE TABLE ADMIN_BOARDS
(
    ID                NUMBER(10,0) NOT NULL,
    ADMIN_BOARD_ID    VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ADMIN_BOARDS_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, ADMIN_BOARD_ID)
);

CREATE SEQUENCE AUTHENTICATION_CERTS_SEQ;
CREATE SEQUENCE AUTHENTICATION_CONTENT_SEQ;
CREATE SEQUENCE PLATFORM_CERTIFICATE_SEQ;
CREATE SEQUENCE TENANT_KEYSTORE_SEQ;
CREATE SEQUENCE ADMIN_BOARDS_SEQ;
