CREATE TABLE COMPUTED_VALUES
(
    ID                       NUMBER(10,0) NOT NULL,
    CHUNK_ID                 NUMBER(10,0),
    ELECTION_EVENT_ID        VARCHAR2(255 CHAR) NOT NULL,
    JSON                     CLOB,
    TENANT_ID                VARCHAR2(255 CHAR) NOT NULL,
    VERIFICATION_CARD_SET_ID VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT COMPUTED_VALUES_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VERIFICATION_CARD_SET_ID, CHUNK_ID)
);

CREATE TABLE MIXDEC_BALLOT_BOX_STATUS
(
    BALLOT_BOX_ID     VARCHAR2(255 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
    ERROR_MESSAGE     VARCHAR2(150 CHAR),
    STATUS            VARCHAR2(10 CHAR) NOT NULL,
    PRIMARY KEY (BALLOT_BOX_ID, ELECTION_EVENT_ID)
);

CREATE TABLE MIXDEC_NODE_OUTPUT
(
    BALLOT_BOX_ID     VARCHAR2(255 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
    NODE_ID           VARCHAR2(255 CHAR) NOT NULL,
    PAYLOAD           BLOB,
    PRIMARY KEY (BALLOT_BOX_ID, ELECTION_EVENT_ID, NODE_ID)
);

CREATE TABLE MIXED_BALLOT_BOX_INFORMATION
(
    ID                    NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID         VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID     VARCHAR2(100 CHAR) NOT NULL,
    ENCRYPTION_PARAMETERS CLOB NOT NULL,
    PUBLIC_KEY            CLOB NOT NULL,
    TENANT_ID             VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PLATFORM_CERTIFICATE
(
    ID                  NUMBER(19,0) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLATFORM_CERTIFICATE_UK1 UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);

CREATE TABLE TENANT_KEYSTORE
(
    ID               NUMBER(19,0) NOT NULL,
    KEY_TYPE         VARCHAR2(100 CHAR) NOT NULL,
    KEYSTORE_CONTENT CLOB NOT NULL,
    PLATFORM_NAME    VARCHAR2(100 CHAR),
    TENANT_ID        VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT TENANT_KEYSTORE_UK1 UNIQUE (PLATFORM_NAME, KEY_TYPE, TENANT_ID)
);

CREATE TABLE OR_PARTIAL_RESULTS
(
    CORRELATION_ID_HI NUMBER(19,0) NOT NULL,
    CORRELATION_ID_LO NUMBER(19,0) NOT NULL,
    RESULT            BLOB NOT NULL
);

CREATE SEQUENCE COMPUTED_VALUES_SEQ;
CREATE SEQUENCE MIXED_BALLOT_BOX_INFORMATION_SEQ;
CREATE SEQUENCE PLATFORM_CERTIFICATE_SEQ;
CREATE SEQUENCE TENANT_KEYSTORE_SEQ;
