CREATE TABLE CREDENTIAL_DATA
(
    ID                NUMBER(10,0) NOT NULL,
    CREDENTIAL_ID     VARCHAR2(255 CHAR) NOT NULL,
    KEYSTORE          CLOB NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ID         VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CREDENTIAL_DATA_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, CREDENTIAL_ID)
);

CREATE TABLE PLATFORM_CERTIFICATE
(
    ID                  NUMBER(19,0) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLATFORM_CERTIFICATE_UK1 UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);

CREATE TABLE VOTER_INFORMATION
(
    ID                       NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID            VARCHAR2(255 CHAR) NOT NULL,
    BALLOT_ID                VARCHAR2(255 CHAR) NOT NULL,
    CREDENTIAL_ID            VARCHAR2(255 CHAR) NOT NULL,
    ELECTION_EVENT_ID        VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ID                VARCHAR2(255 CHAR) NOT NULL,
    VERIFICATION_CARD_ID     VARCHAR2(255 CHAR) NOT NULL,
    VERIFICATION_CARD_SET_ID VARCHAR2(255 CHAR) NOT NULL,
    VOTING_CARD_ID           VARCHAR2(255 CHAR) NOT NULL,
    VOTING_CARD_SET_ID       VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT VOTER_INFORMATION_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID)
);

CREATE SEQUENCE CREDENTIAL_DATA_SEQ;
CREATE SEQUENCE PLATFORM_CERTIFICATE_SEQ;
CREATE SEQUENCE VOTER_INFORMATION_SEQ;
