CREATE TABLE CC_NODE_KEYS
(
    NODE_ID VARCHAR2(10) NOT NULL,
    KEYS    BLOB NOT NULL,
    CONSTRAINT CC_NODE_KEYS_PK PRIMARY KEY (NODE_ID)
);

CREATE TABLE CC_ELECTION_SIGNING_KEYS
(
    NODE_ID           VARCHAR2(10) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100) NOT NULL,
    KEYS              BLOB NOT NULL,
    PASSWORD          BLOB NOT NULL,
    CONSTRAINT CC_ELECTION_SIGNING_KEYS_PK PRIMARY KEY (NODE_ID, ELECTION_EVENT_ID)
);

CREATE TABLE CCM_ELECTION_KEY
(
    NODE_ID                            VARCHAR2(10) NOT NULL,
    ELECTION_EVENT_ID                  VARCHAR2(100) NOT NULL,
    CCMJ_ELECTION_SECRET_KEY           BLOB NOT NULL,
    CCMJ_ELECTION_PUBLIC_KEY           BLOB NOT NULL,
    CCMJ_ELECTION_PUBLIC_KEY_SIGNATURE BLOB NOT NULL,
    CONSTRAINT CCM_ELECTION_KEY_PK PRIMARY KEY (NODE_ID, ELECTION_EVENT_ID)
);
