CREATE TABLE BALLOT
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_ID         VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    SIGNATURE         CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BALLOT_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, BALLOT_ID)
);

CREATE TABLE BALLOT_BOX
(
    ID                  NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID       VARCHAR2(100 CHAR) NOT NULL,
    BALLOT_ID           VARCHAR2(100 CHAR) NOT NULL,
    COMPUTATION_RESULTS BLOB NOT NULL,
    ELECTION_EVENT_ID   VARCHAR2(100 CHAR) NOT NULL,
    TENANT_ID           VARCHAR2(100 CHAR) NOT NULL,
    VOTE                CLOB NOT NULL,
    VOTING_CARD_ID      VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BALLOT_BOX_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID, BALLOT_ID, BALLOT_BOX_ID)
);

CREATE TABLE BALLOT_BOX_CONTENT
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID     VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BALLOT_BOX_CONTENT_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, BALLOT_BOX_ID)
);

CREATE TABLE BALLOT_BOX_INFORMATION
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID     VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    SIGNATURE         CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BALLOT_BOX_INFORMATION_UK1 UNIQUE (BALLOT_BOX_ID, ELECTION_EVENT_ID, TENANT_ID)
);
-- ?? ALTER TABLE BALLOT_BOX_INFORMATION ADD STATUS VARCHAR2(50 BYTE) DEFAULT 'NONE' NOT NULL ;

CREATE TABLE BALLOT_TEXT
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_ID         VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    SIGNATURE         CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BALLOT_TEXT_UK1 UNIQUE (TENANT_ID, BALLOT_ID, ELECTION_EVENT_ID)
);

CREATE TABLE CLEANSED_BALLOT_BOX
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID     VARCHAR2(100 CHAR) NOT NULL,
    BALLOT_ID         VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    ENCRYPTED_VOTE    CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    VOTING_CARD_ID    VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CLEANSED_BALLOT_BOX_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID, BALLOT_ID, BALLOT_BOX_ID)
);

CREATE TABLE ELECTION_PUBLIC_KEY
(
    ID                     NUMBER(10,0) NOT NULL,
    ELECTION_EVENT_ID      VARCHAR2(100 CHAR) NOT NULL,
    ELECTORAL_AUTHORITY_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON                   CLOB NOT NULL,
    TENANT_ID              VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ELECTION_PUBLIC_KEY_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, ELECTORAL_AUTHORITY_ID)
);

CREATE TABLE PLATFORM_CERTIFICATE
(
    ID                  NUMBER(19,0) NOT NULL,
    CERTIFICATE_CONTENT CLOB NOT NULL,
    CERTIFICATE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    PLATFORM_NAME       VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLATFORM_CERTIFICATE_UK1 UNIQUE (PLATFORM_NAME, CERTIFICATE_NAME)
);

CREATE TABLE TENANT_KEYSTORE
(
    ID               NUMBER(19,0) NOT NULL,
    KEY_TYPE         VARCHAR2(100 CHAR) NOT NULL,
    KEYSTORE_CONTENT CLOB NOT NULL,
    PLATFORM_NAME    VARCHAR2(100 CHAR),
    TENANT_ID        VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT TENANT_KEYSTORE_UK1 UNIQUE (PLATFORM_NAME, KEY_TYPE, TENANT_ID)
);

CREATE TABLE ELECTION_INFORMATION_CONTENT
(
    ID                NUMBER(10,0) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    JSON              CLOB NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ELECTION_INFORMATION_CONTENT_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID)
);

CREATE TABLE SUCCESSFUL_VOTES
(
    ID                NUMBER(10,0) NOT NULL,
    BALLOT_BOX_ID     VARCHAR2(100 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    TIMESTAMP         VARCHAR2(255 CHAR) NOT NULL,
    VOTING_CARD_ID    VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT SUCCESSFUL_VOTES_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID, BALLOT_BOX_ID)
);

CREATE TABLE VOTE_CAST_CODE
(
    ID                  NUMBER(10,0) NOT NULL,
    VOTE_CAST_CODE      VARCHAR2(100 CHAR) NOT NULL,
    COMPUTATION_RESULTS BLOB NOT NULL,
    ELECTION_EVENT_ID   VARCHAR2(100 CHAR) NOT NULL,
    TENANT_ID           VARCHAR2(100 CHAR) NOT NULL,
    VOTING_CARD_ID      VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT VOTE_CAST_CODE_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID)
);

CREATE TABLE VOTE_VALIDATION
(
    ID                NUMBER(10,0) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
    TENANT_ID         VARCHAR2(100 CHAR) NOT NULL,
    VOTE_HASH         VARCHAR2(150 CHAR) NOT NULL,
    VOTING_CARD_ID    VARCHAR2(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT VOTE_VALIDATION_UK1 UNIQUE (TENANT_ID, ELECTION_EVENT_ID, VOTING_CARD_ID, VOTE_HASH)
);

CREATE SEQUENCE BALLOT_BOX_CONTENT_SEQ;
CREATE SEQUENCE BALLOT_BOX_INFORMATION_SEQ;
CREATE SEQUENCE BALLOT_BOX_SEQ;
CREATE SEQUENCE BALLOT_SEQ;
CREATE SEQUENCE BALLOT_TEXT_SEQ;
CREATE SEQUENCE CLEANSED_BALLOT_BOX_SEQ;
CREATE SEQUENCE ELECTION_INFORMATION_CONTENT_SEQ;
CREATE SEQUENCE ELECTION_PUBLIC_KEY_SEQ;
CREATE SEQUENCE PLATFORM_CERTIFICATE_SEQ;
CREATE SEQUENCE TENANT_KEYSTORE_SEQ;
CREATE SEQUENCE SUCCESSFUL_VOTES_SEQ;
CREATE SEQUENCE VOTE_CAST_CODE_SEQ;
CREATE SEQUENCE VOTE_VALIDATION_SEQ;
